### ISSUE TITLE
Atari 2600

### ISSUE THREAD

**Issue by okmike87** [thebezelproject/BezelProject#14]
I see the bezel pack here for Atari 2600, but I don't see the option in the RetroPie Bezel Project menu to install and use it. Do we install them manually?

**Comment by thebezelproject** [comment]
Those haven't been made yet, that's why they aren't in the yet.

Only systems that have bezel PNG files created are shown for download.

We're working on systems all the time (Playstation 1 right now) so eventually, we'll get to the Atari 2600 system.

As you can imagine, there's ALOT of PNG files to make for every system.  We'll get there one day.

**Comment by okmike87** [comment]
Oh goodness, I didn't actually look in the folders and see there were no PNG files yet. Sorry for the dumb question and thanks for the reply.

**Comment by thebezelproject** [comment]
Done!
