### ISSUE TITLE
Megadrive

### ISSUE THREAD

**Issue by Shadow322** [thebezelproject/BezelProject#2]
Megadrive set will not install it goes threw the downloading and processing then goes back to the showing not installed

**Comment by chubbypigeon33** [comment]
I'm having the exact same issue.

**Comment by DePeePs** [comment]
Same issue. Tried it today.

**Comment by chubbypigeon33** [comment]
well mom still says not installed but for some reason it's working today lol. Whatever I'll take it

**Comment by matthaynes1901** [comment]
Same problem here, any news on a fix?

**Comment by chewvodka** [comment]
Just to +1 this issue.  I noticed this today when I was installing the bezels.  Says it didn't install (inside the BezelProject menu screens), but the end result when playing a game is that it DID install.

**Comment by chewvodka** [comment]
I spent an evening pondering this, wondering what the problem was.  I think I know to cause, but don't know of a solution...  The problem, I think, comes from how the script stores the artwork path by emulator and not system.  If you have multiple systems using the same emulator (like Mega Drive, Master System, Game Gear), you're going to have problems with overlapping and overwriting of artwork files.  Especially if there are games using the same name.  So it's no wonder it reports that it was not complete.  My theory anyway.

**Comment by shadimirza** [comment]
Same issue here. Megadrive says everything is "done" but it still reads as "not installed" and the bezels don't display in game, even if Megadrive bezels are set to enabled. All other systems are fine. If it helps, I renamed my system to "Genesis" since I'm in the U.S. Not sure if that is causing the issue.

**Comment by thebezelproject** [comment]
With this console it will say not installed even though they are.  If they are still not working for you it's one of two things, you aren't using the no-intro ROM sets or you aren't using the correct emulator as mentioned in setup instructions at the home screen.  Use either lr-pucodrive or lr-genesis-plus-gx

**Comment by jphillip5** [comment]
At least for PicoDrive, the display overlay flag doesn't get turned on.  Simply go into RetroArch, under overlays, turn display overlay on and save the core configuration.

**Comment by xgrind** [comment]
The bug continues to use the script in Emuelec 3.8. All other systems download the game bezels, but the megadrive only downloads the default.

**Comment by thebezelproject** [comment]
Emulec isn't supported by the project because they don't use our installer code, therefore we have no idea where the issue is.

Both our Linux/RetroPie and Windows installers work fine for our Megadrive repository. Please contact the Emulec author.
