### ISSUE TITLE
Feature Request?

### ISSUE THREAD

**Issue by njlovold** [thebezelproject/BezelProject#48]
I haven't found anywhere to submit a feature request, so I thought I'd try here.  Are there any plans to add Sega Model 2 emulator to the Bezel Project?  Thanks.

**Comment by thebezelproject** [comment]
No plans at this point, especially since the Model 2 emulator doesn't natively support bezels. We create bezels first and foremost for systems that are supported on the Raspberry Pi under Retroarch. Having said that, since there is some overlap of the Model 2 game list and MAME games, you could pull the matching games from the MAME pack(s) and create your own Model 2 bezel set.
