### ISSUE TITLE
Bezels install but won't load.

### ISSUE THREAD

**Issue by chewvodka** [thebezelproject/BezelProject#62]
I'm pretty sure this is because I'm not using RetroPie, but a derivative called ARES running on Ubuntu, which is installed on an Atari VCS of all things.  :)  Anyway, I modified the script so it would install all the files in the correct paths (basically changing out all the `/opt/retropie/` paths to `/opt/ares`.  I can get everything to install ok, and it looks like it's made the appropriate changes to activate them.  However, when I launch a game in RetroArch, the bezels don't load.  If I go into the Overlay settings, I can see the selected bezel file has been populated, but it doesn't display (and yes, I have it enabled).  If I click on the filename and browse to the path, I can select the exact same filename and then it loads.  It does this on every single game I've tested it with.  Is there some setting in the script that maybe didn't translate when I modified it?  What should I look for?  It's very annoying not having it automated, and require me to manually select it each time.  Thanks!

**Comment by thebezelproject** [comment]
We can't support using our installer on other systems it is not intended for, however, it sounds like the basic paths were corrected since a bezel can be manually loaded.

There are two things to check if bezels don't auto load. Make sure the rom names match the names for the cfg files found under the Retroarch config directory that matches the core name of the core you are using. Lastly, make sure the name of that core named directory under config is the name the core expects to see. Core names can change over time for different reasons.
